name: Master Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'master' # (main branch) Set branch of the GH repo to push
jobs:
  TelnyxCypress_TestSuite: # Name of the job
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # In command line run “node -v” and choose your version
      - run: npm ci
      #  - run: npm config set script-shell "G:\Git\bin\bash.exe"
      - name: run test
        run: npm run cypress:run # Our name of the headless script
      - name: Publishing Mochawesome Report to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mochawesome
          path: cypress/reports
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: cypress/reports # The folder the action should deploy.
          target-folder: docs
      - name: Pushes docs to another repository
        uses: cpina/github-action-push-to-another-repository@v1.3
        if: always()
        env:
          API_TOKEN_GITHUB: ${{ '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' }} # Instruction where to get token is below
        with:
          source-directory: docs
          destination-github-username: 'KlimovAndrii' # Your username
          destination-repository-name: 'CypressCucumberTelnyxTest' # Name of your repo
          user-email: 'ag.klimov@gmail.com' # Your email
          target-branch: gh-pages